version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-cah
    ports:
      - "5555:5555"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
